print("Count: " + db.tw_samples.find({}).count())
print("IDs  : " + db.tw_samples.distinct('id').length)
print("Users: " + db.tw_samples.distinct('user.id').length)
print("Words: " + db.tw_samples.find({words: {$exists: true}}).count())
print("Train: " + db.tw_samples.find({training_data: true}).count())
print("Test : " + db.tw_samples.find({test_data: true}).count())