print("Training data")
print(db.tw_samples.find({training_data: true, topic_id: 0, words: {$elemMatch: {$eq: "かける"}}}).count())
print(db.tw_samples.find({training_data: true, topic_id: 1, words: {$elemMatch: {$eq: "かける"}}}).count())
print(db.tw_samples.find({training_data: true, topic_id: 2, words: {$elemMatch: {$eq: "かける"}}}).count())
print(db.tw_samples.find({training_data: true, topic_id: 3, words: {$elemMatch: {$eq: "かける"}}}).count())
print(db.tw_samples.find({training_data: true, topic_id: 4, words: {$elemMatch: {$eq: "かける"}}}).count())
print("Test data")
print(db.tw_samples.find({test_data: true, topic_id: 0, words: {$elemMatch: {$eq: "かける"}}}).count())
print(db.tw_samples.find({test_data: true, topic_id: 1, words: {$elemMatch: {$eq: "かける"}}}).count())
print(db.tw_samples.find({test_data: true, topic_id: 2, words: {$elemMatch: {$eq: "かける"}}}).count())
print(db.tw_samples.find({test_data: true, topic_id: 3, words: {$elemMatch: {$eq: "かける"}}}).count())
print(db.tw_samples.find({test_data: true, topic_id: 4, words: {$elemMatch: {$eq: "かける"}}}).count())